language: php

sudo: false

cache:
    directories:
        - "$HOME/.composer/cache"

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    include:
        - php: 7.0
          env: SYMFONY_VERSION="2.3.*"
        - php: 7.0
          env: SYMFONY_VERSION="2.7.*"
        - php: 7.0
          env: SYMFONY_VERSION="2.8.*"
        - php: 7.0
          env: SYMFONY_VERSION="3.0.*"

before_install: if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi

install: composer update

script: phpunit --coverage-clover clover

after_success: curl -sL https://bit.ly/artifact-uploader | php
